version: '3.0'

services:
  app:
    image: 'b50a871c6f35'
    container_name: 'OS_app'
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_URL=jdbc:postgresql://db_p:5432/postgres
    expose:
      - '8090'
    ports:
      - '8090:8090'
    depends_on:
      - 'db_p'
  db_p:
    image: 'postgres'
    container_name: 'db_p'
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
