DROP TABLE IF EXISTS "detail";
DROP TABLE IF EXISTS "order";

CREATE TABLE "order" (
	id          INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"number"    VARCHAR(21) NOT NULL UNIQUE,
	amount      NUMERIC NOT NULL CHECK(amount >= 0.0),
	"date"      date DEFAULT NOW(),
	consumer    VARCHAR(50) NOT NULL,
	address     VARCHAR(100) NOT NULL,
	paymentType VARCHAR(50) NOT NULL,
	deliveryType VARCHAR(50) NOT NULL
	);

CREATE TABLE "detail" (
	id_detail       INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	productCode     INT NOT NULL CHECK(productCode > 0),
	name            VARCHAR(50) NOT NULL,
	quantity        NUMERIC NOT NULL CHECK(quantity > 0),
	unitPrice       NUMERIC NOT NULL CHECK(unitPrice > 0),
	id_order        INT REFERENCES "order"(id)
	);

INSERT INTO public."order" (number, amount, "date", consumer, address, paymentType, deliveryType) VALUES
('1230120241020', 2.5,  '2024-10-20',   'John',     'Kazan',    'cash', 'pickup'),
('1230220241021', 60,   '2024-10-21',   'Adam',     'Moscow',   'card', 'pickup'),
('1230320241022', 24,   '2024-10-22',   'Kate',     'London',   'card', 'delivery'),
('1230420241022', 4450, '2024-10-22',   'Loly',     'Tokio',    'card', 'delivery'),
('1230520241022', 2.5,  '2024-10-22',   'Barbara',  'Nevada',   'cash', 'pickup'),
('4531920241023', 100,  '2024-10-23',   'Mike Koy', 'Nevada',   'cash', 'pickup'),
('7471620241023', 4185,  '2024-10-23',  'Anakonda', 'Amazonka', 'card', 'pickup');

INSERT INTO public.detail (productCode, name, quantity, unitPrice, id_order) VALUES
(111, 'banana',     2,     1.25,   1),
(111, 'banana',     2,     1.25,   2),
(222, 'apple',      1.5,   5,      2),
(333, 'orange',     5,     10,     2),
(444, 'potato',     0.4,   10,     3),
(555, 'carrot',     0.1,   200,    3),
(333, 'orange',     5,     10,     4),
(444, 'potato',     40,    10,     4),
(555, 'carrot',     20,    200,    4),
(111, 'banana',     2,     1.25,   5),
(111, 'banana',     2,     1.25,   6),
(222, 'apple',      1.5,   5,      6),
(333, 'orange',     5,     10,     6),
(555, 'carrot',     0.1,   200,    6),
(444, 'potato',     2,     10,     6),
(444, 'potato',     13.5,  10,     7),
(333, 'orange',     5,     10,     7),
(555, 'carrot',     20,    200,    7);


